manifest:
  remotes:
    # nRF Connect SDK GitHub organization.
    # NCS repositories are hosted here.
    - name: ncs
      url-base: https://github.com/nrfconnect

  projects:
    - name: nrfxlib
      remote: ncs
      repo-path: sdk-nrfxlib
      path: modules/nrfconnect/nrfxlib
      revision: v2.6.0
    - name: hostap
      remote: ncs
      repo-path: sdk-hostap
      path: modules/nrfconnect/hostap
      revision: dda5457ad2cfce99e333980c7764c8d480ae4010
