manifest:
  remotes:
    # nRF Connect SDK GitHub organization.
    # NCS repositories are hosted here.
    - name: ncs
      url-base: https://github.com/nrfconnect

  projects:
    - name: nrfxlib
      remote: ncs
      repo-path: sdk-nrfxlib
      path: modules/nrfconnect/nrfxlib
      revision: v2.7.0
    - name: oberon-psa-crypto
      remote: ncs
      path: modules/crypto/oberon-psa-crypto
      repo-path: sdk-oberon-psa-crypto
      revision: e0800ec5283ba89b2619919ef1889d98a9a79132
    - name: hostap
      remote: ncs
      repo-path: sdk-hostap
      path: modules/nrfconnect/hostap
      revision: 6311fde66f87ac8c8838a2d5fcfe55a498a8682a
