manifest:
  remotes:
    # nRF Connect SDK GitHub organization.
    # NCS repositories are hosted here.
    - name: ncs
      url-base: https://github.com/nrfconnect

  projects:
    - name: nrfxlib
      remote: ncs
      repo-path: sdk-nrfxlib
      path: modules/nrfconnect/nrfxlib
      revision: v2.6.1
    - name: hostap
      remote: ncs
      repo-path: sdk-hostap
      path: modules/nrfconnect/hostap
      revision: e080aa8d0c7706ec5ab74785b3c8accc4973cd86
