manifest:
  remotes:
    # nRF Connect SDK GitHub organization.
    # NCS repositories are hosted here.
    - name: ncs
      url-base: https://github.com/nrfconnect

  projects:
    - name: nrfxlib
      remote: ncs
      repo-path: sdk-nrfxlib
      path: modules/nrfconnect/nrfxlib
      revision: v3.0.2
    - name: oberon-psa-crypto
      remote: ncs
      path: modules/crypto/oberon-psa-crypto
      repo-path: sdk-oberon-psa-crypto
      revision: v1.3.4-ncs1-2
